### ISSUE TITLE
DHCP Server Offering IPs to All Clients

### ISSUE THREAD

**Issue by bias-keenly** [mpetazzoni/ptftpd#16]
First, I want to say I think this is a terrific project and concept.  Thank you for making it.

I have been testing the PXE / DHCP server functionality for a project I am working on.  The documentation states that the DHCP server is only supposed to respond to PXE requests.  Only responding to PXE requests is the desired behavior for my use case as well.  I have found that the DHCP server is responding to all clients, including phones, watches, etc. and offering the IP addresses.  

The current code checks for the existence of DHCP option 55 to determine if the request is PXE related or not.  From my research, DHCP option 55 is the parameter request list, and is included in most or all DHCP requests.  All requests I have received when running this include option 55, PXE or not.  Please see the following Cisco support article for a wireshark look at option 55.  https://www.cisco.com/c/en/us/support/docs/security/identity-services-engine/116235-configure-ise-00.html

One solution that I have found is to check if option 60 (vendor class identifier) begins with `PXEClient`.  I have seen articles and open source PXE systems that suggest using the option 60 to determine PXE clients and only send these clients the next server and bootfile options.  This is also how you determine if the PXE request is EUFI or BIOS.  https://wiki.fogproject.org/wiki/index.php/BIOS_and_UEFI_Co-Existence 

I will submit a PR shortly with this proposed change.

**Comment by mpetazzoni** [comment]
Closing this as the PRs have been merged. Thanks!
