### ISSUE TITLE
Data block number starting on 0 makes server incompatible with RFC 1350 

### ISSUE THREAD

**Issue by estevE11** [mpetazzoni/ptftpd#36]
I had to implement a TFTP Client with RFC 1350 specifications for class and I think I found a bug where, when sending a file from client, the server expects first DATA block number to be 0 when it should be 1.

Here is what the [documentation](https://datatracker.ietf.org/doc/html/rfc1350#:~:text=The%0A%20%20%20block%20numbers%20on%20data%20packets%20begin%20with%20one%20and%20increase%20by%20one%20for%0A%20%20%20each%20new%20block%20of%20data.) says: "The block numbers on **data packets begin with one** and increase by one for each new block of data."

Got into the code and printed the number the server receives and the one it expects. They are different so it stops the transfer.
![image](https://github.com/mpetazzoni/ptftpd/assets/15111802/aaa9ba3d-d0da-42b7-9db7-60577e8ac998)

Is this a bug or is it intentional and I'm missing something?

**Comment by estevE11** [comment]
There's a fix already #31

**Comment by mpetazzoni** [comment]
Thanks!
